- Bag of Words
- TF-IDF
- Word2Vec

<br><br><br><br>

# Bag of Words

In [1]:
import pandas as pd
df=pd.read_csv('spam_ham_dataset.csv').drop('Unnamed: 0',axis=1)
df=df[:500]

In [2]:
df.head()

  label                                               text  label_num
0   ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3  spam  Subject: photoshop , windows , office . cheap ...          1
4   ham  Subject: re : indian springs\r\nthis deal is t...          0

In [3]:
# data cleaning and preprocessing
import re
import nltk

In [4]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

stemmer=SnowballStemmer('english')

In [5]:
corpus=[]
for i in range(len(df)):
    text=df.iloc[i]['text'].strip()
    retext=re.sub('[^a-zA-Z]',' ',text)
    retext=retext.lower()
    words=[]
    for word in retext.split(' '):
        if word not in stopwords.words('english') and word != '':
            word=stemmer.stem(word)
            words.append(word.strip())
    text=' '.join(words)
    df.iloc[i]['text']=text
df

C:\Users\Ansh Vaid\AppData\Local\Temp\ipykernel_14080\3927275030.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[i]['text']=text

    label                                               text  label_num
0     ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1     ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2     ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3    spam  Subject: photoshop , windows , office . cheap ...          1
4     ham  Subject: re : indian springs\r\nthis deal is t...          0
..    ...                                                ...        ...
495   ham  Subject: eastrans nomination change effective ...          0
496  spam  Subject: look . . . here derm\r\nhuge offer fo...          1
497   ham  Subject: enron / hpl actuals for october 4 , 2...          0
498  spam  Subject: assimilate promiscuity capricorn barc...          1
499  spam                    Subject: no more injections\r\n          1

[500 rows x 3 columns]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
model=CountVectorizer(max_features=500) # Top 500 frequent words are used

In [7]:
x=model.fit_transform(df['text'][:350])
x.toarray()

array([[1, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 8, 0, 2],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
x[4].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 3,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [9]:
model.vocabulary_

{'subject': 414,
 'enron': 164,
 'meter': 287,
 'this': 439,
 'is': 240,
 'up': 458,
 'to': 445,
 'the': 431,
 'you': 497,
 'on': 326,
 'monday': 292,
 '00': 0,
 'flow': 179,
 'data': 132,
 'by': 101,
 'daren': 131,
 'please': 354,
 'daily': 130,
 'volume': 467,
 'activity': 54,
 'can': 104,
 'from': 187,
 'gas': 196,
 'change': 109,
 'needed': 304,
 'for': 181,
 'hpl': 224,
 'nom': 311,
 'january': 249,
 '2001': 24,
 'see': 390,
 'attached': 80,
 'file': 175,
 '09': 10,
 'xls': 494,
 'we': 472,
 're': 367,
 'that': 430,
 'most': 296,
 'time': 444,
 'of': 320,
 'year': 496,
 'know': 256,
 'and': 71,
 'it': 242,
 'think': 438,
 'about': 48,
 'past': 342,
 'but': 98,
 'does': 149,
 'go': 203,
 'week': 474,
 'december': 140,
 '25': 31,
 'through': 441,
 'what': 478,
 'like': 263,
 'out': 339,
 'at': 79,
 'was': 470,
 'because': 87,
 'are': 76,
 'with': 485,
 'going': 205,
 'date': 133,
 'following': 180,
 '12': 14,
 '13': 15,
 'now': 317,
 'need': 303,
 'all': 63,
 'agree': 61,
 'us': 459,
 'get': 199,
 'have': 212,
 'some': 404,
 'our': 338,
 'before': 89,
 'into': 238,
 'be': 86,
 'without': 487,
 'so': 402,
 'how': 222,
 'then': 434,
 'let': 262,
 'me': 283,
 'which': 481,
 'first': 178,
 'option': 332,
 'would': 492,
 'done': 152,
 'could': 125,
 'country': 126,
 'www': 493,
 'com': 115,
 'where': 480,
 'in': 231,
 'also': 66,
 'only': 330,
 'one': 328,
 '15': 17,
 'here': 215,
 'each': 156,
 'other': 337,
 'just': 254,
 'second': 386,
 'houston': 221,
 'trade': 450,
 'off': 321,
 'as': 78,
 'much': 297,
 'email': 160,
 'back': 83,
 'your': 499,
 'if': 229,
 'available': 82,
 'will': 484,
 'soon': 405,
 'end': 162,
 'way': 471,
 'no': 310,
 'do': 148,
 'great': 208,
 'or': 333,
 'office': 324,
 'deal': 138,
 'book': 95,
 'teco': 422,
 'my': 299,
 'received': 369,
 'an': 70,
 'there': 435,
 'price': 357,
 'continue': 121,
 'down': 153,
 'address': 58,
 'message': 286,
 'due': 154,
 'needs': 305,
 'http': 227,
 'should': 398,
 'made': 273,
 'those': 440,
 'who': 483,
 'savings': 385,
 'take': 419,
 '30': 36,
 'save': 384,
 'when': 479,
 'use': 460,
 'online': 329,
 'special': 407,
 'below': 91,
 'receive': 368,
 'day': 135,
 'sale': 381,
 'thursday': 442,
 'march': 279,
 '22': 28,
 'today': 446,
 'mail': 274,
 'offer': 322,
 'many': 278,
 'items': 243,
 'already': 65,
 'click': 112,
 'must': 298,
 'any': 73,
 'not': 315,
 'set': 396,
 '21': 27,
 'free': 185,
 'don': 151,
 'new': 307,
 'products': 362,
 'terms': 424,
 'manager': 277,
 'details': 144,
 'purchase': 364,
 'prior': 359,
 'gift': 200,
 '01': 2,
 'future': 191,
 'looking': 271,
 'best': 92,
 'make': 275,
 'net': 306,
 'delivery': 141,
 'than': 427,
 'million': 290,
 'got': 207,
 'want': 469,
 'more': 295,
 'high': 216,
 'low': 272,
 '100': 12,
 'god': 204,
 'she': 397,
 'noms': 313,
 'actual': 55,
 '26': 32,
 'forwarded': 183,
 'melissa': 285,
 'texas': 425,
 'utilities': 462,
 '02': 3,
 '27': 33,
 '10': 11,
 'am': 67,
 'david': 134,
 'tu': 453,
 'cc': 106,
 'mmbtu': 291,
 '23': 29,
 '2000': 23,
 'stock': 412,
 'inc': 232,
 'top': 448,
 'month': 294,
 'april': 75,
 'its': 244,
 'next': 309,
 'days': 136,
 'news': 308,
 'agreement': 62,
 'services': 395,
 'expect': 168,
 'company': 118,
 'phone': 352,
 'software': 403,
 'global': 202,
 'development': 145,
 'over': 340,
 'voip': 466,
 'including': 234,
 'companies': 117,
 'call': 102,
 'service': 394,
 'has': 211,
 'created': 127,
 'internet': 237,
 'information': 236,
 'world': 491,
 'long': 269,
 'customers': 129,
 'their': 432,
 'changes': 110,
 'via': 465,
 'entered': 165,
 'sales': 382,
 'access': 50,
 'north': 314,
 'help': 214,
 'business': 97,
 'using': 461,
 'rate': 366,
 'such': 415,
 'words': 488,
 'within': 486,
 'forward': 182,
 'statements': 410,
 'section': 387,
 'securities': 388,
 'act': 53,
 'performance': 349,
 'fact': 169,
 'may': 282,
 'based': 85,
 'number': 318,
 'risks': 377,
 'stocks': 413,
 'investment': 239,
 'advice': 59,
 'report': 373,
 'look': 270,
 '17': 19,
 'these': 436,
 'after': 60,
 'been': 88,
 'above': 49,
 'since': 399,
 'security': 389,
 'send': 391,
 'include': 233,
 'were': 477,
 '60': 41,
 '2004': 25,
 'actuals': 56,
 'august': 81,
 '28': 34,
 'tap': 420,
 '20': 22,
 '000': 1,
 'tenaska': 423,
 'iv': 245,
 'july': 252,
 'remove': 371,
 'demand': 142,
 '50': 39,
 'thanks': 429,
 'megan': 284,
 'issue': 241,
 'transactions': 451,
 'oo': 331,
 'management': 276,
 'people': 347,
 'money': 293,
 '80': 43,
 'every': 167,
 'website': 473,
 'system': 418,
 'sure': 416,
 'had': 210,
 'said': 380,
 '14': 16,
 'market': 280,
 '24': 30,
 '99': 46,
 '29': 35,
 'risk': 376,
 'under': 456,
 'additional': 57,
 'bankruptcy': 84,
 'accounting': 52,
 'sources': 406,
 'vance': 463,
 'sitara': 400,
 'bob': 94,
 'taylor': 421,
 '04': 5,
 'pm': 355,
 'robert': 378,
 'cotten': 124,
 'hou': 220,
 'ect': 158,
 'julie': 251,
 'meyers': 288,
 'lisa': 266,
 'susan': 417,
 'smith': 401,
 'production': 361,
 'line': 265,
 'ticket': 443,
 'volumes': 468,
 'fyi': 193,
 'wellhead': 476,
 'contract': 122,
 'howard': 223,
 'camp': 103,
 'james': 247,
 'mary': 281,
 'steve': 411,
 'michael': 289,
 'lauri': 259,
 'gco': 197,
 'gary': 195,
 'carlos': 105,
 'rodriguez': 379,
 'pat': 343,
 'clynes': 113,
 'corp': 123,
 'tom': 447,
 'na': 300,
 'farmer': 170,
 '07': 8,
 '06': 7,
 'jackie': 246,
 'young': 498,
 'plant': 353,
 'two': 455,
 'them': 433,
 'further': 190,
 '19': 21,
 '08': 9,
 'katherine': 255,
 '18': 20,
 'fred': 184,
 'once': 327,
 '11': 13,
 'contact': 120,
 'direct': 147,
 'research': 375,
 'fw': 192,
 'original': 336,
 'sent': 392,
 'tuesday': 454,
 'hope': 218,
 '05': 6,
 '03': 4,
 'find': 177,
 '16': 18,
 'both': 96,
 'questions': 365,
 'less': 261,
 'per': 348,
 'transport': 452,
 'equistar': 166,
 'september': 393,
 'start': 409,
 'good': 206,
 'until': 457,
 'friday': 186,
 '31': 37,
 'while': 482,
 'they': 437,
 'october': 319,
 'very': 464,
 'oil': 325,
 'energy': 163,
 'working': 490,
 'prices': 358,
 'related': 370,
 'being': 90,
 'last': 258,
 'well': 475,
 'field': 174,
 '40': 38,
 'crude': 128,
 'natural': 302,
 'did': 146,
 'work': 489,
 'account': 51,
 'product': 360,
 'dollars': 150,
 'allocation': 64,
 'iferc': 230,
 'total': 449,
 'nomination': 312,
 'ami': 69,
 'chokshi': 111,
 'thank': 428,
 'name': 301,
 'buy': 99,
 'order': 334,
 'desk': 143,
 '713': 42,
 'reply': 372,
 'lloyd': 268,
 'buyback': 100,
 'effective': 159,
 'th': 426,
 'hsc': 226,
 'same': 383,
 'jan': 248,
 'he': 213,
 'his': 217,
 'november': 316,
 'group': 209,
 'another': 72,
 'america': 68,
 'give': 201,
 'path': 344,
 'list': 267,
 '90': 44,
 'fax': 171,
 'personal': 350,
 'dvd': 155,
 'computron': 119,
 'offers': 323,
 'request': 374,
 'june': 253,
 'feb': 172,
 'february': 173,
 'fuel': 188,
 'co': 114,
 'deals': 139,
 'provide': 363,
 'id': 228,
 'gap': 194,
 'certificates': 108,
 'aol': 74,
 'lee': 260,
 'hotmail': 219,
 'john': 250,
 'stack': 408,
 'limit': 264,
 'orders': 335,
 'between': 93,
 'pg': 351,
 'ena': 161,
 '500': 40,
 'yap': 495,
 'hplc': 225,
 'papayoti': 341,
 'la': 257,
 'eastrans': 157,
 'point': 356,
 'increase': 235,
 'full': 189,
 'de': 137,
 '202': 26,
 '98': 45,
 'artprice': 77,
 'financial': 176,
 'pefs': 346,
 'pec': 345,
 'gcs': 198,
 'cec': 107,
 'committee': 116,
 'abdv': 47}

In [10]:
model=CountVectorizer(max_features=500,ngram_range=(2,3)) # Top 500 frequent words are used

In [11]:
x=model.fit_transform(df['text'][:350])
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
x[4].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [13]:
model.vocabulary_

{'subject enron': 377,
 'this is': 429,
 'up to': 455,
 'to the': 449,
 'you can': 491,
 'subject hpl': 380,
 'hpl nom': 227,
 'nom for': 302,
 'see attached': 366,
 'attached file': 73,
 'hpl nom for': 228,
 'see attached file': 367,
 'of the': 309,
 'that this': 397,
 'that it': 395,
 'you to': 497,
 'on the': 323,
 'at the': 69,
 'for the': 180,
 'going to': 204,
 'to change': 440,
 'the following': 405,
 'you need': 494,
 'need to': 300,
 'to get': 444,
 'into the': 244,
 'can be': 85,
 'we can': 465,
 'on that': 322,
 'let me': 267,
 'me know': 284,
 'the first': 404,
 'would be': 483,
 'to have': 445,
 'we have': 466,
 'in the': 241,
 'one of': 325,
 'of our': 307,
 'that we': 398,
 'if you': 234,
 'as soon': 65,
 'soon as': 375,
 'as possible': 64,
 'by the': 82,
 'to do': 443,
 'let me know': 268,
 'as soon as': 66,
 'subject re': 382,
 'this deal': 426,
 'it is': 250,
 'there is': 424,
 'know what': 262,
 'we are': 464,
 'continue to': 112,
 'this message': 431,
 'message is': 290,
 'due to': 131,
 'needs to': 301,
 'to be': 437,
 'should be': 369,
 'enron com': 157,
 'this message is': 432,
 'foot locker': 175,
 'in our': 239,
 'to your': 452,
 'and the': 58,
 'click below': 101,
 'is not': 248,
 'in this': 242,
 'through the': 436,
 'and other': 56,
 'please see': 347,
 'must be': 296,
 'the time': 418,
 'will not': 476,
 'do not': 128,
 'wish to': 477,
 'to receive': 447,
 'the best': 401,
 'to make': 446,
 'that you': 399,
 'you will': 499,
 'actual flow': 37,
 'flow for': 172,
 'forwarded by': 184,
 'texas utilities': 391,
 'on 02': 316,
 '2001 10': 27,
 'am to': 48,
 'david avila': 123,
 'avila lsp': 74,
 'lsp enserch': 277,
 'enserch us': 168,
 'us tu': 456,
 'charlie stone': 93,
 'utilities tu': 458,
 'com cc': 107,
 'cc subject': 89,
 'david avila lsp': 124,
 'avila lsp enserch': 75,
 'lsp enserch us': 278,
 'texas utilities tu': 392,
 '23 2000': 29,
 'for your': 183,
 'will be': 472,
 'the month': 408,
 'month of': 295,
 'and will': 59,
 'with the': 478,
 'over the': 334,
 'the world': 422,
 'want to': 462,
 'entered into': 169,
 'access to': 35,
 'from the': 189,
 'such as': 385,
 'within this': 479,
 'this email': 427,
 'looking statements': 274,
 'the securities': 416,
 'act of': 36,
 'are not': 62,
 'and may': 55,
 'may be': 281,
 'based on': 76,
 'number of': 306,
 'use of': 457,
 'investment advice': 245,
 'this report': 435,
 'that the': 396,
 'of this': 311,
 'this newsletter': 434,
 'about the': 34,
 'the company': 402,
 'does not': 130,
 'prior to': 351,
 'of these': 310,
 'have been': 212,
 'the above': 400,
 'is an': 246,
 'and should': 57,
 'within this report': 480,
 'of this report': 312,
 'enron hpl': 162,
 'hpl actuals': 222,
 'actuals for': 38,
 '2000 teco': 25,
 'teco tap': 389,
 '000 enron': 1,
 '000 hpl': 2,
 'hpl gas': 224,
 'gas daily': 198,
 'subject enron hpl': 378,
 'enron hpl actuals': 163,
 'hpl actuals for': 223,
 '2000 teco tap': 26,
 'hpl gas daily': 225,
 'tenaska iv': 390,
 'the price': 411,
 'on this': 324,
 'company has': 109,
 'as the': 67,
 'the website': 421,
 'is for': 247,
 'some of': 373,
 'has been': 209,
 'ooking statements': 326,
 'subject to': 384,
 'that is': 394,
 'the publisher': 412,
 'publisher of': 352,
 'the information': 407,
 'many of': 279,
 'these companies': 425,
 'you have': 492,
 'some of the': 374,
 'the publisher of': 413,
 'publisher of this': 353,
 'based on the': 77,
 'created and': 120,
 'and entered': 53,
 'in sitara': 240,
 'vance taylor': 459,
 '02 23': 7,
 'pm to': 349,
 'to robert': 448,
 'robert cotten': 359,
 'cotten hou': 117,
 'hou ect': 216,
 'ect ect': 137,
 'ect cc': 133,
 'julie meyers': 256,
 'meyers hou': 292,
 'susan smith': 386,
 'smith hou': 370,
 'melissa graves': 287,
 'graves hou': 205,
 'ect subject': 153,
 'into sitara': 243,
 'the deal': 403,
 'vlt 6353': 461,
 'taylor hou': 387,
 'ect on': 151,
 'pm from': 348,
 'clem cernosek': 100,
 'ect robert': 152,
 'ect howard': 148,
 'howard camp': 220,
 'camp hou': 83,
 'ect mary': 150,
 'lauri allen': 263,
 'allen hou': 44,
 'enron enron': 158,
 'gco enron': 199,
 'ect gary': 147,
 'gary hanks': 196,
 'hanks hou': 207,
 'carlos rodriguez': 87,
 'rodriguez hou': 363,
 'pat clynes': 337,
 'clynes corp': 103,
 'corp enron': 113,
 'na enron': 297,
 'ect daren': 135,
 'daren farmer': 121,
 'farmer hou': 170,
 'robert cotten hou': 360,
 'cotten hou ect': 118,
 'hou ect ect': 217,
 'ect ect cc': 138,
 'julie meyers hou': 257,
 'meyers hou ect': 293,
 'smith hou ect': 371,
 'melissa graves hou': 288,
 'graves hou ect': 206,
 'ect ect subject': 145,
 'vance taylor hou': 460,
 'taylor hou ect': 388,
 'hou ect on': 218,
 'ect ect robert': 144,
 'ect ect howard': 141,
 'ect howard camp': 149,
 'howard camp hou': 221,
 'camp hou ect': 84,
 'ect ect mary': 142,
 'ect ect michael': 143,
 'lauri allen hou': 264,
 'allen hou ect': 45,
 'gco enron enron': 200,
 'ect ect gary': 140,
 'gary hanks hou': 197,
 'hanks hou ect': 208,
 'carlos rodriguez hou': 88,
 'rodriguez hou ect': 364,
 'pat clynes corp': 338,
 'clynes corp enron': 104,
 'corp enron enron': 114,
 'na enron enron': 298,
 'ect ect daren': 139,
 'ect daren farmer': 136,
 'daren farmer hou': 122,
 'farmer hou ect': 171,
 'ect cc subject': 134,
 'mary poorman': 280,
 'enron on': 166,
 'on 04': 318,
 'am from': 47,
 'enron enronxgate': 161,
 '25 2001': 31,
 'jackie young': 254,
 'enron subject': 167,
 'is the': 249,
 'jackie young hou': 255,
 'enron enron subject': 160,
 'will need': 475,
 'so that': 372,
 '19 2000': 15,
 '2000 08': 21,
 '2000 04': 20,
 'aimee lannou': 39,
 'subject fw': 379,
 'original message': 328,
 'message from': 289,
 'for you': 182,
 'on 05': 319,
 'enron cc': 155,
 'there are': 423,
 'know if': 260,
 'have any': 210,
 'any questions': 60,
 'original message from': 329,
 'corp enron on': 115,
 'enron enron cc': 159,
 'me know if': 285,
 'know if you': 261,
 'if you have': 236,
 'you have any': 493,
 'have any questions': 211,
 'for this': 181,
 'all of': 42,
 'oil and': 314,
 'and gas': 54,
 'at this': 70,
 'natural gas': 299,
 'we will': 467,
 'as well': 68,
 'this gas': 428,
 'of you': 313,
 'you are': 490,
 'for all': 176,
 'not be': 305,
 'for october': 179,
 '11 2000': 12,
 'hpl iferc': 226,
 'the gas': 406,
 '13 2000': 13,
 '2000 03': 19,
 'ami chokshi': 51,
 '2000 02': 18,
 '2000 10': 23,
 '000 hpl iferc': 3,
 'thank you': 393,
 'to this': 450,
 'it to': 251,
 'to you': 451,
 'http www': 233,
 'what you': 469,
 'you think': 496,
 'in order': 237,
 'it will': 253,
 'reply to': 357,
 'the volumes': 420,
 'from robert': 187,
 'robert lloyd': 361,
 'by robert': 81,
 'lloyd hou': 271,
 'on 03': 317,
 'do you': 129,
 'you want': 498,
 'from robert lloyd': 188,
 'forwarded by robert': 186,
 'robert lloyd hou': 362,
 'lloyd hou ect': 272,
 'megan parker': 286,
 'on 07': 320,
 'to daren': 441,
 'did not': 127,
 'this meter': 433,
 'have the': 213,
 'the same': 415,
 'can you': 86,
 'to daren farmer': 442,
 '00 am': 0,
 '2000 09': 22,
 'subject new': 381,
 'enron north': 164,
 'north america': 303,
 'america corp': 49,
 'corp from': 116,
 'cc subject re': 90,
 'enron north america': 165,
 'north america corp': 304,
 'america corp from': 50,
 'out of': 332,
 'ali duty': 40,
 'duty free': 132,
 'www computron': 486,
 'computron me': 110,
 'me com': 283,
 'this mail': 430,
 'request for': 358,
 'would like': 484,
 'like to': 269,
 'are the': 63,
 'may not': 282,
 'ali duty free': 41,
 'www computron me': 487,
 'computron me com': 111,
 'would like to': 485,
 '30 000': 32,
 'by ami': 79,
 'chokshi corp': 98,
 'on 01': 315,
 '2000 11': 24,
 'com on': 108,
 'forwarded by ami': 185,
 'by ami chokshi': 80,
 'ami chokshi corp': 52,
 'chokshi corp enron': 99,
 'enron cc subject': 156,
 '16 2000': 14,
 'money back': 294,
 'click here': 102,
 'for march': 178,
 '2000 01': 17,
 'please let': 345,
 'pm to daren': 350,
 'please let me': 346,
 'lone star': 273,
 'all the': 43,
 'order to': 327,
 'in order to': 238,
 'fw gap': 192,
 'gap gift': 194,
 'gift certificates': 203,
 'aol com': 61,
 'hotmail com': 215,
 'fw gap gift': 193,
 'gap gift certificates': 195,
 'top of': 453,
 'of stack': 308,
 'limit orders': 270,
 'way to': 463,
 'the system': 417,
 'set up': 368,
 '90 days': 33,
 'top of stack': 454,
 'it was': 252,
 'well as': 468,
 'deal ticket': 125,
 'the office': 409,
 'out of the': 333,
 'chevron phillips': 96,
 'phillips chemical': 343,
 'chemical co': 94,
 'co lp': 105,
 'lp hplc': 275,
 'hplc 04': 229,
 '04 01': 8,
 '01 sales': 5,
 'sales buyback': 365,
 '10 000': 10,
 'hsc flw': 231,
 'flw high': 173,
 'high gdp': 214,
 'lee papayoti': 265,
 'papayoti hou': 335,
 'chevron phillips chemical': 97,
 'phillips chemical co': 344,
 'chemical co lp': 95,
 'co lp hplc': 106,
 'lp hplc 04': 276,
 'hplc 04 01': 230,
 '04 01 sales': 9,
 '01 sales buyback': 6,
 'hsc flw high': 232,
 'flw high gdp': 174,
 'lee papayoti hou': 266,
 'papayoti hou ect': 336,
 'fuels cotton': 190,
 'cotton valley': 119,
 'fuels cotton valley': 191,
 'to cc': 438,
 'to cc subject': 439,
 'the only': 410,
 'on 12': 321,
 'will have': 474,
 'ect enron': 146,
 'will continue': 473,
 'if you are': 235,
 '20 2000': 16,
 'the volume': 419,
 'for an': 177,
 '25 2000': 30,
 'july 2000': 258,
 'how to': 219,
 'ect subject re': 154,
 'you please': 495,
 'the sale': 414,
 'personal research': 342,
 're meter': 354,
 'meter 1266': 291,
 'allocation exception': 46,
 '21 2000': 28,
 'subject re meter': 383,
 'ots enron': 330,
 'ots enron enron': 331,
 '000 mmbtu': 4,
 '10 100': 11,
 'refurb 90': 355,
 'xph 10': 488,
 'wifi refurb': 470,
 'refurb 90 days': 356,
 'xph 10 100': 489,
 'wifi refurb 90': 471,
 'sources said': 376,
 'katherine herrera': 259,
 'pefs pec': 340,
 'pec pec': 339,
 'gcs cec': 201,
 'cec pec': 91,
 'pefs pec pec': 341,
 'gcs cec pec': 202,
 'cec pec pec': 92,
 'atlantis business': 71,
 'business development': 78,
 'development corporation': 126,
 'atlantis business development': 72,
 'words words': 481,
 'words words words': 482}

<br><br><br><br>

# TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
model2=TfidfVectorizer(max_features=500)

In [15]:
x=model2.fit_transform(df['text'][:350])
x.toarray()

array([[0.17160223, 0.        , 0.        , ..., 0.21286146, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.14322543, 0.        ,
        0.04609357],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [16]:
x[3].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.96657021,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.2564021 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [17]:
model2.vocabulary_

{'subject': 414,
 'enron': 164,
 'meter': 287,
 'this': 439,
 'is': 240,
 'up': 458,
 'to': 445,
 'the': 431,
 'you': 497,
 'on': 326,
 'monday': 292,
 '00': 0,
 'flow': 179,
 'data': 132,
 'by': 101,
 'daren': 131,
 'please': 354,
 'daily': 130,
 'volume': 467,
 'activity': 54,
 'can': 104,
 'from': 187,
 'gas': 196,
 'change': 109,
 'needed': 304,
 'for': 181,
 'hpl': 224,
 'nom': 311,
 'january': 249,
 '2001': 24,
 'see': 390,
 'attached': 80,
 'file': 175,
 '09': 10,
 'xls': 494,
 'we': 472,
 're': 367,
 'that': 430,
 'most': 296,
 'time': 444,
 'of': 320,
 'year': 496,
 'know': 256,
 'and': 71,
 'it': 242,
 'think': 438,
 'about': 48,
 'past': 342,
 'but': 98,
 'does': 149,
 'go': 203,
 'week': 474,
 'december': 140,
 '25': 31,
 'through': 441,
 'what': 478,
 'like': 263,
 'out': 339,
 'at': 79,
 'was': 470,
 'because': 87,
 'are': 76,
 'with': 485,
 'going': 205,
 'date': 133,
 'following': 180,
 '12': 14,
 '13': 15,
 'now': 317,
 'need': 303,
 'all': 63,
 'agree': 61,
 'us': 459,
 'get': 199,
 'have': 212,
 'some': 404,
 'our': 338,
 'before': 89,
 'into': 238,
 'be': 86,
 'without': 487,
 'so': 402,
 'how': 222,
 'then': 434,
 'let': 262,
 'me': 283,
 'which': 481,
 'first': 178,
 'option': 332,
 'would': 492,
 'done': 152,
 'could': 125,
 'country': 126,
 'www': 493,
 'com': 115,
 'where': 480,
 'in': 231,
 'also': 66,
 'only': 330,
 'one': 328,
 '15': 17,
 'here': 215,
 'each': 156,
 'other': 337,
 'just': 254,
 'second': 386,
 'houston': 221,
 'trade': 450,
 'off': 321,
 'as': 78,
 'much': 297,
 'email': 160,
 'back': 83,
 'your': 499,
 'if': 229,
 'available': 82,
 'will': 484,
 'soon': 405,
 'end': 162,
 'way': 471,
 'no': 310,
 'do': 148,
 'great': 208,
 'or': 333,
 'office': 324,
 'deal': 138,
 'book': 95,
 'teco': 422,
 'my': 299,
 'received': 369,
 'an': 70,
 'there': 435,
 'price': 357,
 'continue': 121,
 'down': 153,
 'address': 58,
 'message': 286,
 'due': 154,
 'needs': 305,
 'http': 227,
 'should': 398,
 'made': 273,
 'those': 440,
 'who': 483,
 'savings': 385,
 'take': 419,
 '30': 36,
 'save': 384,
 'when': 479,
 'use': 460,
 'online': 329,
 'special': 407,
 'below': 91,
 'receive': 368,
 'day': 135,
 'sale': 381,
 'thursday': 442,
 'march': 279,
 '22': 28,
 'today': 446,
 'mail': 274,
 'offer': 322,
 'many': 278,
 'items': 243,
 'already': 65,
 'click': 112,
 'must': 298,
 'any': 73,
 'not': 315,
 'set': 396,
 '21': 27,
 'free': 185,
 'don': 151,
 'new': 307,
 'products': 362,
 'terms': 424,
 'manager': 277,
 'details': 144,
 'purchase': 364,
 'prior': 359,
 'gift': 200,
 '01': 2,
 'future': 191,
 'looking': 271,
 'best': 92,
 'make': 275,
 'net': 306,
 'delivery': 141,
 'than': 427,
 'million': 290,
 'got': 207,
 'want': 469,
 'more': 295,
 'high': 216,
 'low': 272,
 '100': 12,
 'god': 204,
 'she': 397,
 'noms': 313,
 'actual': 55,
 '26': 32,
 'forwarded': 183,
 'melissa': 285,
 'texas': 425,
 'utilities': 462,
 '02': 3,
 '27': 33,
 '10': 11,
 'am': 67,
 'david': 134,
 'tu': 453,
 'cc': 106,
 'mmbtu': 291,
 '23': 29,
 '2000': 23,
 'stock': 412,
 'inc': 232,
 'top': 448,
 'month': 294,
 'april': 75,
 'its': 244,
 'next': 309,
 'days': 136,
 'news': 308,
 'agreement': 62,
 'services': 395,
 'expect': 168,
 'company': 118,
 'phone': 352,
 'software': 403,
 'global': 202,
 'development': 145,
 'over': 340,
 'voip': 466,
 'including': 234,
 'companies': 117,
 'call': 102,
 'service': 394,
 'has': 211,
 'created': 127,
 'internet': 237,
 'information': 236,
 'world': 491,
 'long': 269,
 'customers': 129,
 'their': 432,
 'changes': 110,
 'via': 465,
 'entered': 165,
 'sales': 382,
 'access': 50,
 'north': 314,
 'help': 214,
 'business': 97,
 'using': 461,
 'rate': 366,
 'such': 415,
 'words': 488,
 'within': 486,
 'forward': 182,
 'statements': 410,
 'section': 387,
 'securities': 388,
 'act': 53,
 'performance': 349,
 'fact': 169,
 'may': 282,
 'based': 85,
 'number': 318,
 'risks': 377,
 'stocks': 413,
 'investment': 239,
 'advice': 59,
 'report': 373,
 'look': 270,
 '17': 19,
 'these': 436,
 'after': 60,
 'been': 88,
 'above': 49,
 'since': 399,
 'security': 389,
 'send': 391,
 'include': 233,
 'were': 477,
 '60': 41,
 '2004': 25,
 'actuals': 56,
 'august': 81,
 '28': 34,
 'tap': 420,
 '20': 22,
 '000': 1,
 'tenaska': 423,
 'iv': 245,
 'july': 252,
 'remove': 371,
 'demand': 142,
 '50': 39,
 'thanks': 429,
 'megan': 284,
 'issue': 241,
 'transactions': 451,
 'oo': 331,
 'management': 276,
 'people': 347,
 'money': 293,
 '80': 43,
 'every': 167,
 'website': 473,
 'system': 418,
 'sure': 416,
 'had': 210,
 'said': 380,
 '14': 16,
 'market': 280,
 '24': 30,
 '99': 46,
 '29': 35,
 'risk': 376,
 'under': 456,
 'additional': 57,
 'bankruptcy': 84,
 'accounting': 52,
 'sources': 406,
 'vance': 463,
 'sitara': 400,
 'bob': 94,
 'taylor': 421,
 '04': 5,
 'pm': 355,
 'robert': 378,
 'cotten': 124,
 'hou': 220,
 'ect': 158,
 'julie': 251,
 'meyers': 288,
 'lisa': 266,
 'susan': 417,
 'smith': 401,
 'production': 361,
 'line': 265,
 'ticket': 443,
 'volumes': 468,
 'fyi': 193,
 'wellhead': 476,
 'contract': 122,
 'howard': 223,
 'camp': 103,
 'james': 247,
 'mary': 281,
 'steve': 411,
 'michael': 289,
 'lauri': 259,
 'gco': 197,
 'gary': 195,
 'carlos': 105,
 'rodriguez': 379,
 'pat': 343,
 'clynes': 113,
 'corp': 123,
 'tom': 447,
 'na': 300,
 'farmer': 170,
 '07': 8,
 '06': 7,
 'jackie': 246,
 'young': 498,
 'plant': 353,
 'two': 455,
 'them': 433,
 'further': 190,
 '19': 21,
 '08': 9,
 'katherine': 255,
 '18': 20,
 'fred': 184,
 'once': 327,
 '11': 13,
 'contact': 120,
 'direct': 147,
 'research': 375,
 'fw': 192,
 'original': 336,
 'sent': 392,
 'tuesday': 454,
 'hope': 218,
 '05': 6,
 '03': 4,
 'find': 177,
 '16': 18,
 'both': 96,
 'questions': 365,
 'less': 261,
 'per': 348,
 'transport': 452,
 'equistar': 166,
 'september': 393,
 'start': 409,
 'good': 206,
 'until': 457,
 'friday': 186,
 '31': 37,
 'while': 482,
 'they': 437,
 'october': 319,
 'very': 464,
 'oil': 325,
 'energy': 163,
 'working': 490,
 'prices': 358,
 'related': 370,
 'being': 90,
 'last': 258,
 'well': 475,
 'field': 174,
 '40': 38,
 'crude': 128,
 'natural': 302,
 'did': 146,
 'work': 489,
 'account': 51,
 'product': 360,
 'dollars': 150,
 'allocation': 64,
 'iferc': 230,
 'total': 449,
 'nomination': 312,
 'ami': 69,
 'chokshi': 111,
 'thank': 428,
 'name': 301,
 'buy': 99,
 'order': 334,
 'desk': 143,
 '713': 42,
 'reply': 372,
 'lloyd': 268,
 'buyback': 100,
 'effective': 159,
 'th': 426,
 'hsc': 226,
 'same': 383,
 'jan': 248,
 'he': 213,
 'his': 217,
 'november': 316,
 'group': 209,
 'another': 72,
 'america': 68,
 'give': 201,
 'path': 344,
 'list': 267,
 '90': 44,
 'fax': 171,
 'personal': 350,
 'dvd': 155,
 'computron': 119,
 'offers': 323,
 'request': 374,
 'june': 253,
 'feb': 172,
 'february': 173,
 'fuel': 188,
 'co': 114,
 'deals': 139,
 'provide': 363,
 'id': 228,
 'gap': 194,
 'certificates': 108,
 'aol': 74,
 'lee': 260,
 'hotmail': 219,
 'john': 250,
 'stack': 408,
 'limit': 264,
 'orders': 335,
 'between': 93,
 'pg': 351,
 'ena': 161,
 '500': 40,
 'yap': 495,
 'hplc': 225,
 'papayoti': 341,
 'la': 257,
 'eastrans': 157,
 'point': 356,
 'increase': 235,
 'full': 189,
 'de': 137,
 '202': 26,
 '98': 45,
 'artprice': 77,
 'financial': 176,
 'pefs': 346,
 'pec': 345,
 'gcs': 198,
 'cec': 107,
 'committee': 116,
 'abdv': 47}

<br><br><br><br>

# Word2Vec

In [74]:
from gensim.models import Word2Vec

sentences = [["the", "cat", "sat", "on", "the", "mat"],
             ["the", "dog", "barked"],
             ["the", "dog", "sat", "on", "the", "rug"],
             ['the','sky','is','blue']]

# Training Word2Vec on our sentences
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4) 

vector = model.wv['the']
print(vector)

[-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -1.5080082e-03  2.4697948e-03 -8.8802696e-04  5.5336617e-03
 -2.7429771e-03  2.2600652e-03  5.4557943e-03  8.3459532e-03
 -1.4537406e-03 -9.2081428e-03  4.3705525e-03  5.7178497e-04
  7.4419081e-03 -8.1328274e-04 -2.6384138e-03 -8.7530091e-03
 -8.5655687e-04  2.8265631e-03  5.4014288e-03  7.0526563e-03
 -5.7031214e-03  1.8588197e-03  6.0888636e-03 -4.7980510e-03
 -3.1072604e-03  6.7976294e-03  1.6314756e-03  1.8991709e-04
  3.4736372e-03  2.1777749e-04  9.6188262e-03  5.0606038e-03
 -8.9173904e-03 -7.0415605e-03  9.0145587e-04  6.3925339e-03]

In [75]:
model.predict_output_word(['the', 'cat', 'sat','on'], topn=5)

[('on', 0.090909384),
 ('rug', 0.090909265),
 ('is', 0.090909235),
 ('cat', 0.090909235),
 ('barked', 0.0909092)]

In [77]:
model.predict_output_word(['the', 'sky', 'is'], topn=15)

[('blue', 0.090910524),
 ('is', 0.09091052),
 ('cat', 0.09090994),
 ('sky', 0.09090947),
 ('on', 0.090909466),
 ('barked', 0.090909384),
 ('sat', 0.09090868),
 ('rug', 0.09090818),
 ('mat', 0.090908095),
 ('the', 0.09090805),
 ('dog', 0.09090764)]

In [68]:
model2 = Word2Vec([['the']], vector_size=100, window=1, min_count=1, workers=4)
model2.wv['the']

array([-5.3622725e-04,  2.3643136e-04,  5.1033497e-03,  9.0092728e-03,
       -9.3029495e-03, -7.1168090e-03,  6.4588725e-03,  8.9729885e-03,
       -5.0154282e-03, -3.7633716e-03,  7.3805046e-03, -1.5334714e-03,
       -4.5366134e-03,  6.5540518e-03, -4.8601604e-03, -1.8160177e-03,
        2.8765798e-03,  9.9187379e-04, -8.2852151e-03, -9.4488179e-03,
        7.3117660e-03,  5.0702621e-03,  6.7576934e-03,  7.6286553e-04,
        6.3508903e-03, -3.4053659e-03, -9.4640139e-04,  5.7685734e-03,
       -7.5216377e-03, -3.9361035e-03, -7.5115822e-03, -9.3004224e-04,
        9.5381187e-03, -7.3191668e-03, -2.3337686e-03, -1.9377411e-03,
        8.0774371e-03, -5.9308959e-03,  4.5162440e-05, -4.7537340e-03,
       -9.6035507e-03,  5.0072931e-03, -8.7595852e-03, -4.3918253e-03,
       -3.5099984e-05, -2.9618145e-04, -7.6612402e-03,  9.6147433e-03,
        4.9820580e-03,  9.2331432e-03, -8.1579173e-03,  4.4957981e-03,
       -4.1370760e-03,  8.2453608e-04,  8.4986202e-03, -4.4621765e-03,
        4.5175003e-03, -6.7869602e-03, -3.5484887e-03,  9.3985079e-03,
       -1.5776526e-03,  3.2137157e-04, -4.1406299e-03, -7.6826881e-03,
       -1.5080082e-03,  2.4697948e-03, -8.8802696e-04,  5.5336617e-03,
       -2.7429771e-03,  2.2600652e-03,  5.4557943e-03,  8.3459532e-03,
       -1.4537406e-03, -9.2081428e-03,  4.3705525e-03,  5.7178497e-04,
        7.4419081e-03, -8.1328274e-04, -2.6384138e-03, -8.7530091e-03,
       -8.5655687e-04,  2.8265631e-03,  5.4014288e-03,  7.0526563e-03,
       -5.7031214e-03,  1.8588197e-03,  6.0888636e-03, -4.7980510e-03,
       -3.1072604e-03,  6.7976294e-03,  1.6314756e-03,  1.8991709e-04,
        3.4736372e-03,  2.1777749e-04,  9.6188262e-03,  5.0606038e-03,
       -8.9173904e-03, -7.0415605e-03,  9.0145587e-04,  6.3925339e-03],
      dtype=float32)

In [69]:
model2.predict_output_word(['sky', 'is'], topn=3)

In [70]:
model2.predict_output_word(['the','sky', 'is'], topn=3)

[('the', 1.0)]

In [73]:
model2.wv.most_similar('the', topn=5)

[]